name: Backport PR to Develop

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create backport branch
        run: |
          git fetch origin develop
          git checkout -b backport/main-to-develop
          git merge origin/develop --no-ff -m "Merge main into develop for backport"

      - name: Push backport branch
        run: |
          git push origin backport/main-to-develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Backport: Merge main into develop"
          body: "This is an automated PR to backport changes from main to develop."
          head: backport/main-to-develop
          base: develop
          labels: "backport,automated"