name: Block Feature PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          ALLOWED_BRANCHES=("hotfix/*" "fix/*" "release/*")
          PR_BRANCH="$GITHUB_HEAD_REF"

          # Verifica se a branch do PR está na lista de branches permitidas
          for allowed_branch in "${ALLOWED_BRANCHES[@]}"; do
            if [[ $PR_BRANCH == $allowed_branch ]]; then
              echo "PR from branch '$PR_BRANCH' is allowed."
              exit 0
            fi
          done

          # Se a branch não estiver na lista permitida, bloqueia o PR
          echo "PRs from branch '$PR_BRANCH' are not allowed to main."
          echo "Allowed branches are: ${ALLOWED_BRANCHES[*]}"
          exit 1